### PR TITLE
Battery tuning

### PR DESCRIPTION
**Pull request by yaqwsx**

### CODE REVIEW

**Comment by JarekParal** [comment]
Do you check DRC @yaqwsx?

image

Is that OK?

**Comment by yaqwsx** [comment]
Yes, it is Ok - polygon with no net connection overflow the board outlines. It does not make any harm.

**Comment by JarekParal** [comment]
Could we merge this pull-request or do you have some comments? @TVavrinec @JakubAndrysek

**Comment by JarekParal** [comment]
Due to merging conflict and wrong commit in this branch (`ele: Add line sensor`) was created new branch and merge in PR #30.

**Pull request closed without merging**
